#!/bin/sh

  # putting a number of hotspot and network commands in this script with general directions
  # network manager command line interface
  #
  #
  ## Quick status of all interfaces
  # nmcli dev status

# Detailed overview of all interfaces
  # nmcli

# Get a list of all WiFi SSIDs
#  nmcli d wifi list

# Disconnect from a WiFi network
# nmcli con  # Get the NAME of the WiFi connection
# nmcli con down "connection_name_here"

# Connect to a WiFi network on a specific WiFi interface
# sudo nmcli d wifi connect "ssid_here" password "password_here" ifname wlan1
  # Turn on your hotspot
  # sudo nmcli device wifi hotspot ssid <your_hotspot_name> password <your_hotspot_password> ifname wlan0
  # Turn off a hotspot
  # sudo nmcli connection down <hotspot_connection_name>
  # connect to an existing network
  # sudo nmcli device wifi connect <SSID> password <password>

  # See: https://www.jeffgeerling.com/blog/2023/nmcli-wifi-on-raspberry-pi-os-12-bookworm

  # iwlist

  # sudo nmcli device wifi connect <SSID> password <password>
  # scan for names (SSIDs) of available networks
  # sudo iwlist scan | grep ESSID


